### ISSUE TITLE
Websocket API not working with DISABLE_WEBAPP=true

### ISSUE THREAD

**Issue by cen1** [blockscout/blockscout#10140]
### Description

6.6.0 fixed `DISABLE_WEBAPP=true` however there seems to be unintended? side effect of websockets no longer working. FE can connect and exchange the initial messages (transactions:new_transaction, blocks:new_block) and get's an OK response back but after that no events are pushed down to the FE. I suspect part of the implementation that is responsible to push events has been removed by accident.

If I recompile with `DISABLE_WEBAPP=false` it starts working again.

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

geth

### Backend version

v6.6.0-beta

### Frontend version

v1.30.1

### Elixir & Erlang/OTP versions

v1.14.5 (erlang 25)

### Operating system

Ubuntu

**Comment by cen1** [comment]
Events do not come to the browser (new blocks are not appearing in the UI live). In WS network I only see the initial handshake:

![Screenshot_20240528_111843](https://github.com/blockscout/blockscout/assets/1158861/be52cde9-aeef-4b5e-814a-5cf920206b83)


Setup is a split api/indexer:

VM 1: frontend + backend with `DISABLE_WEBAPP=true`
VM 2: backend indexer with `DISABLE_WEBAPP=true`
Common database for both backends.

/socket/* requests are routed at the LB to indexer backend. 

From my investigation everything works fine, frontend establishes WS connection with the indexer backend it's just that no new block events are received. If I recompile and run with `DISABLE_WEBAPP=false` everything starts working in identical setup.

**Comment by Qwerty5Uiop** [comment]
Thank you, I see the problem. In the current implementation it is expected that if you run a separate setup, there would be an indexer instance and API or web instance. Module that is responsible for sending DB events is started when you set `DISABLE_WEBAPP=true` or `DISABLE_API=true` since such instance is being considered as indexer instance. Module that is responsible for listen these events is started when you set `DISABLE_INDEXER=true` since such instance is considered as API/Web instance.
In your setup both instances are considered as indexer instance since it's enabled for both of them, so the listener process doesn't start at all.

The correct solution would be to set `DISABLE_INDEXER=true` for the first instance since it's only frontend + backend API. In that case it will start the listener process and will receive events from the second instance.

**Comment by cen1** [comment]
Ah I see, we do actually set `DISABLE_INDEXER=true` on the API instance so I think we just need to stop sending /socket to indexer and send it to the API instead which should be listening for the events in this case.

Will test this out now and close if solved.

**Comment by cen1** [comment]
Working fine, closing
