### ISSUE TITLE
Add tokenId for ERC-721 to tokenlist/tokenbalance API

### ISSUE THREAD

**Issue by ValeryVa** [blockscout/blockscout#1074]
Hi there!

It would be great to get tokenId instead of 0 value in the response from /tokenlist and /tokenbalance APIs in case of ERC-721. This change will help to avoid unnecessary requests to backend and the information about tokens will be full and consistent.

Thanks!

**Comment by valeryvaskabovich** [comment]
Hi @sabondano! @acravenho told that you are working with GraphQL API. Is there any way to get this info via GraphQL API instead of modifying existing REST? We are currently building a wallet and having this information in one call will dramatically reduce the amount of requests to the server. Thanks!

**Comment by vbaranov** [comment]
@saneery let's extend `/tokenlist` with token type. I guess it shouldn't slow down the API request.

`/tokenbalance` is specifically for getting balance value. Extending the response will increase response time due to joining one more table in the DB. And in order to supply backward compatibility, the solution will look clunky. I wouldn't suppose to change it.
