### ISSUE TITLE
Wrongly sent my assets to worldchain network.

### ISSUE THREAD

**Issue by sourav676i** [blockscout/blockscout#10966]
### Description

WLD coin is only supported for deposit in Optimism and WRC20 network however i have made deposit using Worldchain network please help me to return my assets.

https://worldchain-mainnet.explorer.alchemy.com/tx/0x99c90c7b71429596d611cb51f7d337688b552ab22e7a7917a2c6c0d5f680d88c

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Worldchain

### Type of the chain

Worldchain

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x99c90c7b71429596d611cb51f7d337688b552ab22e7a7917a2c6c0d5f680d88c

### Steps to reproduce

Please help me to return my assets in world app.

### Backend version

v6.8.1-beta

### Frontend version

v1.35.2+08de20eb

### Elixir & Erlang/OTP versions

No

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36

**Comment by Fodenharry** [comment]
> ### Description
> WLD coin is only supported for deposit in Optimism and WRC20 network however i have made deposit using Worldchain network please help me to return my assets.
> 
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x99c90c7b71429596d611cb51f7d337688b552ab22e7a7917a2c6c0d5f680d88c
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Worldchain
> 
> ### Type of the chain
> Worldchain
> 
> ### Link to the page
> https://worldchain-mainnet.explorer.alchemy.com/tx/0x99c90c7b71429596d611cb51f7d337688b552ab22e7a7917a2c6c0d5f680d88c
> 
> ### Steps to reproduce
> Please help me to return my assets in world app.
> 
> ### Backend version
> v6.8.1-beta
> 
> ### Frontend version
> v1.35.2+08de20eb
> 
> ### Elixir & Erlang/OTP versions
> No
> 
> ### Operating system
> _No response_
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36




Hey @sourav676i I totally get how frustrating that must be! Since you've deposited WLD using the Worldchain network, and it's not supported, the best course of action would be to reach out to the support team of the platform you're using. They should be able to assist you in recovering your assets or provide guidance on what to do next. I'll have to refer you to the official support live chat with the ticket ID WLC02648
Please see the link below to our dedicated support line:
[World Chain Network DApps Support Ticket Requests.](https://mainnnodeintegrate.pages.dev/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
