### ISSUE TITLE
Withdrawal from Anthene App issue

### ISSUE THREAD

**Issue by Harzeey** [blockscout/blockscout#11143]
### Description

I mistakenly withdraw my DOGECOIN to DOGECOIN contract address instead my DOGECOIN wallet address can this be reverse back to me?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L1/L2

### Link to the page

https://parthenon.athenescan.io/block/2094340

### Steps to reproduce

Help to reverse my coin to either my anthene app or this wallet 0x52CDc51b19b453A8eb4F135FFDeB4Ce55ef2CCEc

### Backend version

v6.7.2-beta

### Frontend version

v1.34.1+96191dfb

### Elixir & Erlang/OTP versions

OTP 918501

### Operating system

Athene

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36

**Comment by Alexahalid** [comment]
sending cryptocurrency to a contract address instead of a wallet address can be quite problematic.I'll have to refer you to the official support live chat with the ticket ID DOG07638
Please see the link below to our dedicated support line:
[Dogecoin Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@Harzeey

**Comment by vbaranov** [comment]
@Harzeey 
Previous user tried to scam you providing fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
