### ISSUE TITLE
Not receive.

### ISSUE THREAD

**Issue by Khyrvlz** [blockscout/blockscout#11302]
### Description

Hi, i not recieve the coin into my wallet(ku coin).
Can i get back my coin.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

BEP20

### Type of the chain

WLD

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xa9fb273e774471332797d9a6c51cb36e315ec6934a6c2061a76a47ef6097ccb4

### Steps to reproduce

Can i get back my wld coin.I didn't know ku koin wallet can't accept it.please!!!

### Backend version

v6.9.1-beta

### Frontend version

v1.36.2+f793609b

### Elixir & Erlang/OTP versions

Elixir 1.17.3

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Vickynicole** [comment]
Hello @Khyrvlz 
Since you didn't receive the coin in your KuCoin wallet, I'd recommend you might want to reach out to the official support live chat with the ticket ID KUC07638
Please see the link below to our dedicated support line:
[Kucoin Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by vbaranov** [comment]
@Khyrvlz The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
