### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by DouglasPalacio** [blockscout/blockscout#11398]
### Description

Subject: Claim for Unfairly Reduced Reward in my World Coin Wallet

Dear World Coin Support Team,

I am writing to express my deep disappointment and frustration regarding the reward I was expecting to receive in my World Coin wallet. After patiently waiting for a month, I found out that the reward I had been promised was drastically reduced without any explanation.

Originally, I was informed that I would receive 53.85 World Coin as a reward for my participation and wait. However, when I tried to claim my reward, I was only given 4.08 World Coin. This reduction is unfair, and I feel deeply disappointed by the lack of transparency and communication from your team.

I would like to highlight that my expectation of receiving the full reward was based on the information you provided me and the trust I had placed in your platform. The reduction of the reward without explanation has damaged my trust in World Coin and has caused me great discouragement.

Therefore, I respectfully request that you review this matter and take the necessary steps to correct this error. I would like to receive the full reward of 53.85 World Coin that I was promised.

I appreciate your attention to this matter and look forward to a prompt and satisfactory response.

Sincerely,

Douglas 

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Erigon

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x5703ba88be4855f94ce7406dc2c200614d11ab667edbbbcb828544a2ddf35e36

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

 Elixir 1.17.3 (compiled with Erlang/ OTP 27)

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by Lewis-Dianne** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Blockscout Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by vbaranov** [comment]
This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
