### ISSUE TITLE
Usdc send but not reflecting 

### ISSUE THREAD

**Issue by Samsondanie** [blockscout/blockscout#11394]
### Description

How can I retrieve my asset

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygonedge

### Type of the chain

L2

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0x910a15f37d5c01d5d0694a985967aba41ba0ab0a8ea3b529928eb6fa9fe2797f?tab=token_transfers

### Steps to reproduce

Using address .

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Otp

### Operating system

Linux

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by MJayden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Blockscout Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by Dababebeaut** [comment]
@Samsondanie 
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Blockscout Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by sl1depengwyn** [comment]
This repo is for Blockscout-related questions. Blockscout is an open source blockchain explorer. Thus, your question is out of scope, where the Blockscout team can help, you better contact the chain support directly.
