### ISSUE TITLE
No me llega el dinero, quisiera actualizar mi CCI para el destino

### ISSUE THREAD

**Issue by AngiedeJ** [blockscout/blockscout#11423]
### Description

En octubre me hice una transferencia de monedas que decía en dos días y todavía no me llega, y cambie de cuenta de banco si pudiera cambiar mis datos de destino o mejor un desembolso de mis monedas 
![Screenshot_2024-10-23-15-34-16-157_com worldcoin](https://github.com/user-attachments/assets/38ea0ae1-e3ca-41cb-b29d-a429a748a18d)

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

.

### Type of the chain

.

### Link to the page

https://worldchain-mainnet.explorer.alchemy.com/tx/0xfc49353e4bc83a06a48d9e28b4ff027326ed8305e10d3ee51116a2637f6112ef

### Steps to reproduce

.

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

.

### Operating system

.

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by billflame** [comment]
Hi There @AngiedeJ
I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Bluewallet Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by vbaranov** [comment]
@AngiedeJ The previous user tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
