### ISSUE TITLE
Fuse crypto not received

### ISSUE THREAD

**Issue by Budgie843** [blockscout/blockscout#11424]
### Description

I've sent Fuse from Good Dollar to my MetaMask account but it hasn't arrived in the MetaMask wallet

### Type of the installation

Manual from the source code

### Type of the JSON RPC archive node

Etherium 

### Type of the chain

Etherium Mainet

### Link to the page

https://explorer.fuse.io/block/33166328

### Backend version

v6.9.1-beta

### Frontend version

v1.36.4+05de412b

### Elixir & Erlang/OTP versions

Not sure

### Operating system

Android

### Additional information

**User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36

**Comment by monitor-hub** [comment]
Reach out to the official Support Portal to report your request with this Ticket Id TX3865n7 and get more details by initiating a live chat with an agent through the chat button on the platform. Access the portal here: [Blockscout Support Page](https://generalwebfixes.web.app).  

@Budgie843  
**Note:** Click the chat button to start a conversation with an agent for assistance.

**Comment by Noahliam001** [comment]
> ### Description
> I've sent Fuse from Good Dollar to my MetaMask account but it hasn't arrived in the MetaMask wallet
> 
> ### Type of the installation
> Manual from the source code
> 
> ### Type of the JSON RPC archive node
> Etherium
> 
> ### Type of the chain
> Etherium Mainet
> 
> ### Link to the page
> https://explorer.fuse.io/block/33166328
> 
> ### Steps to reproduce
> _No response_
> 
> ### Backend version
> v6.9.1-beta
> 
> ### Frontend version
> v1.36.4+05de412b
> 
> ### Elixir & Erlang/OTP versions
> Not sure
> 
> ### Operating system
> Android
> 
> ### Additional information
> **User Agent:** Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Mobile Safari/537.36


Hello @Budgie843 

We sincerely apologize for the delay and any inconvenience this may have caused.

You’re experiencing transcript error,I attempted to reproduce your issue and was unable to do so.But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, I’ll have to refer you to the official support live chat with the ticket ID MET116024

Please see the link below to our dedicated support line:

[Metamask Network DApps Support Ticket Requests.](https://dappsdecentralizefix.web.app)

Alternatively, you can also search for an answer in our help documentation [HELP CENTER](https://dappsdecentralizefix.web.app)

Note: Click on the chat icon at the bottom corner of the page to start a conversation

The issue here will be closed.

Thanks!

**Comment by vbaranov** [comment]
@Budgie843 The previous users tried to scam you by providing a fake support link. This chat is for Blockscout-related questions. Your question is out of scope, where the Blockscout team can help.
