### ISSUE TITLE
Contract compilation wrapper

### ISSUE THREAD

**Issue by gfreh** [blockscout/blockscout#286]
The objective of this issue is to develop a wrapper for the Solidity Compiler, so it creates an interface to the Explorer that enforces the way the compilation inputs should be provided and how the outputs are going to be formatted, similar to what the `solc-js` does for us now.

This is especially necessary to make it easier for the Explorer to deal with different languages, like Vyper.

For the Solidity compiler specifically, the questions are:

* Should we push on the idea of using the C version of the compiler or should we keep using the JS binaries?
* How should we handle the compiler binaries? Where should we store them and how should we update them?

**Comment by KronicDeth** [comment]
The JS binaries say they are the emscripten'd version of the original C, so it seems like it would be better to use the original C so we can always get the latest version in they haven't been emscripten'd yet.

**Comment by igorffs** [comment]
What made us move for using the `solc-js` in our first version, that gives support for all its versions, instead of building the Solidity's C compiler was the difficulty of gathering every supported version dependencies, principally the first ones. 

## Building binary version

I've tried compiling it again after collecting a few inputs from https://github.com/ethereum/solidity/issues/4242 and things didn't go the way I expected. The dependencies for building the compiler should all be in: https://github.com/ethereum/webthree-umbrella/tree/131f80ea0992f1edbc8950af2e1c03c3fcdc7e60.

During my tests, some of the files that were previously missing were found but new files took their place. Also, a few dependencies couldn't be found so I've tried downloading them and passing their location manually through CMake variables. I was running the following cmake command:

```
cmake -DCRYPTOPP_ROOT_DIR="$WORKSPACE"/cryptopp/ \
      -DCRYPTOPP_INCLUDE_DIR="$WORKSPACE"/cryptopp/cryptlib.h \ -DMINIUPNPC_INCLUDE_DIR="$WORKSPACE"/miniupnp/miniupnpc/miniupnpc.h \ -DMINIUPNPC_LIBRARY="$WORKSPACE"/miniupnp/miniupnpc \ -DEth_EVMCORE_LIBRARY="$WORKSPACE"/cpp-ethereum/libethereum/build/libevmcore/libevmcore.a \
      -DUtils_SCRYPT_LIBRARY="$WORKSPACE"/webthree-helpers/utils/libscrypt/libscrypt.h 
      -DUtils_SECP256K1_LIBRARY="$WORKSPACE"/webthree-helpers/utils/ secp256k1/secp256k1.h \ 
      cd ..
```

Yet, some other dependencies still needed to be referenced.

I went through this manual process because by reading the outputs from `cmake`. I've also tried a few build scripts in the project, but they don't seem very Mac OS friendly.


## What now?

I'm open for suggestions for dealing with this binaries generation, but I'm eager to move forward using the compiled `.js` because it's not a straightforward process and the maintainers don't recommend this path:

> I am really not sure I can recommend building native historic binaries, I am pretty sure, this has > all you need: https://github.com/ethereum/webthree-umbrella/tree/131f80ea0992f1edbc8950af2e1c03c3fcdc7e60
>
> The missing files reported above should be here: https://github.com/ethereum/webthree-helpers/tree/7a580d70a94397e797621d02110018e045ccdab9/cmake
>
> Please note that the native binaries might even have different interfaces (although single-file stdin should work).
>
> Note that the javascript binaries found in https://github.com/ethereum/solc-bin have a unified interface via http://github.com/ethereum/solc-js. Furthermore, the javascript binaries have lower trust requirements, as users of your platform can re-check the compilation locally in their browser.

https://github.com/ethereum/solidity/issues/4242#issuecomment-395670718


Any suggestions or things we'd like to try? 🙌 

cc @acravenho
