### ISSUE TITLE
Number of Validators

### ISSUE THREAD

**Issue by JamesLawton** [blockscout/blockscout#2877]
As an enhancement to the block explorer, I would like to see the total number of validators that are currently on chain via the getValidators() function from the smart contract. Ideally, this would be shown on the homepage to give an overview of how decentralized the current chain is. Any suggestions on where to modify this in particular? I would be happy to make a pull request on further investigation

**Comment by vbaranov** [comment]
Goog initiative. Here is where `getValidators()` method is used in order to retrieve validators metadata for POA based chains https://github.com/poanetwork/blockscout/blob/7788f4efd33e2c8f22a388a4eaf4434720c422bc/apps/explorer/lib/explorer/validator/metadata_retriever.ex#L19

The contract which exposes this method is added with `VALIDATORS_CONTRACT` environment variable https://docs.blockscout.com/for-developers/information-and-settings/env-variables

**Comment by gabrielrumiranda** [comment]
Can I take this issue ?
