### ISSUE TITLE
Different Transaction and Block Count 

### ISSUE THREAD

**Issue by M-Hammad-Ali** [blockscout/blockscout#4449]
The block count and transaction count on the explorer are different for the two simultaneously opened browser tabs as shown in the figure:
![image](https://user-images.githubusercontent.com/55716079/127308454-65c48d38-35d6-40c9-89d2-f3ef15a795b0.png)

**Observations**
- If one transaction occurs the count is increment by one and then starts incrementing automatically. Again shift to correct count on page reloading.
- The block count is different until the new block is mine and then sync. 
- Same behaviour has been observed on the other blockscout explorers like Celo.

**Reproduce Issue**
- Open the blockscout explorer on one tab and note the transaction and block count.
- Now open the same explorer on the other tab and compare the number. It'll be different.
- Whenever a new transaction occurs the transaction increment once and then start increment that makes a huge difference on the two different tx counts. On reloading, it'll again shift to the correct that will be a small number than before.

**Required Behaviour**
- The block count and transaction count should be the same on the different tabs. 
- Also transaction count should increment only once.

@konstantinzolotarev @atoulme @KronicDeth @ohrite @fvictorio

**Comment by vbaranov** [comment]
This intended behavior by design. For performance purposes, when you refresh the page the number of transactions is taken from the cache. When transactions are coming Blockscout increments counter value but didn't update cache on every transaction is coming, again for performance reasons. The cache itself is updating by the background process. The frequency of the update is managed by TXS_COUNT_CACHE_PERIOD env variable (the list of en variables for the reference https://docs.blockscout.com/for-developers/information-and-settings/env-variables). By default, the period of cache update is set to 2 hours.

**Comment by M-Hammad-Ali** [comment]
Got it
@vbaranov thanks for informing.

**Comment by c-spider** [comment]
What is the best period time for TXS_COUNT_CACHE_PERIOD? And I cannot find the exact varialble "TXS_COUNT_CACHE_PERION" from above link. What's wrong with me?

**Comment by vbaranov** [comment]
@c-spider in the current master branch all env variables which have "_CACHE_" prefix were renamed to use `CACHE_` prefix for better naming. So, instead `TXS_COUNT_CACHE_PERIOD`, it is `CACHE_TXS_COUNT_PERIOD`. We will update in the docs once issue new release. As about the best value, it depends how long the query `SELECT COUNT(1) FROM TRANSACTIONS;` executing on the indexed chain. Usually, for long production chains it may take half an hour, 1 hour.

**Comment by c-spider** [comment]
Thanks. @vbaranov
