### ISSUE TITLE
[High] xDai API issue 

### ISSUE THREAD

**Issue by MrLuit** [blockscout/blockscout#4451]
(Not sure if this is the right place to report issues on the API, feel free to point me to the right person/team to handle this.)

---

Under certain conditions, API returns an unexpected 504 through Cloudflare. 

### Steps to reproduce

1. Open URL: https://blockscout.com/xdai/mainnet/api?module=logs&action=getLogs&fromBlock=0&toBlock=latest&topic0=0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef&address=0xcB3BB4CCe15b492E7fdD7cb9a3835C034714207A

### Expected behaviour

API should either return a list of all results, or if limited by the amount of results, return the first n results so I can use the `fromBlock` parameter on the latest result (I believe that's how etherscan handles it).

### Actual behaviour

![image](https://user-images.githubusercontent.com/12037024/127337232-87791e54-8fa5-4530-8ba0-b0bd03c7958d.png)

**Comment by vbaranov** [comment]
`getLogs` API endpoint works as you described. However, since you request from genesis block to the head of the chain, the request hits timeout. This request is heavy enough, because the `logs` is the one of the largest table in the Blockscout DB and complex enough since it involves `transactions` and `internal_transactions` tables. In order to mitigate hitting request timeout, you should decrease the range of blocks and request step by step in ranges.

I downloaded from the DB the list of all logs (actually, 10) records for the address, that you requested.
[logs_0xcB3BB4CCe15b492E7fdD7cb9a3835C034714207A.txt](https://github.com/blockscout/blockscout/files/7013285/logs_0xcB3BB4CCe15b492E7fdD7cb9a3835C034714207A.txt).

I will keep this issue open, in case we will find how to simplify the current complex query, but the general advice, for now, is to decrease the blocks range in the request.

**Comment by vbaranov** [comment]
Speed of `logs` api endpoint improved. Sample request from the issue is not timing out anymore. Please let us know, if you still experience similar issue.
