### ISSUE TITLE
Search results page 

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#4495]
Show a dedicated search results page if there are multiple search results in the search dropdown and user hits Enter (now results in 404 error). 

1) Add pagination or load more search results on scroll. 
2) (Optional) Add number of search results 
3) Add division by category  (maybe a filter by Category or sections in Search results)
- Address
- Token 
- Transactions
- Blocks
- Labels
4) If possible, show search results for any search string (currently minimum is 4 chars) 

![image](https://user-images.githubusercontent.com/6618204/128687771-980d9eab-97b9-47bf-ab62-e112c0d8364d.png)

**Comment by vbaranov** [comment]
@ulyanas Pagination and embedded search filed are added in this PR https://github.com/blockscout/blockscout/pull/4489. See the screenshot in the PR for visual changes. The changes from the PR have been deployed to the Sokol instance. I suggest working on pagination enhancements in the frame of Pagination epic, and items list enhancements like adding of loading spinner to the Items list epic. Displaying categories also depends on pagination since we want to see the number of search results in each category.
