### ISSUE TITLE
Moonriver: the cancel transaction does not work

### ISSUE THREAD

**Issue by biggwb** [blockscout/blockscout#4631]
Trying to cancel my stuck transaction on blockscout on the moonbeam network the cancel button does not work.
if I was on the ETH network I would cancel my transaction by sending 0 amount and use the same nonce number with a high gas price, by using My Etherwallet app.  how can I do the samething on the blockscout mooonbeam network, MEW does not work. 

when I click the cancel button it says "please unlock 0x444.....5455 in metamask" and when I do that nothing happens, I pulled out the 2nd laptop and clicked on the cancel button to the same tx number and it still does nothing

### Environment
* Elixir Version: 1.11.4
* Erlang Version: 23
* BlockScout Version: v3.7.0+

* User Agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by vbaranov** [comment]
The cancel pending transaction feature was removed from the master branch of the Blockscout repository since it was discovered that MetaMask doesn't support changing nonce in transactions on the API level. This button should be removed in Moonriver Blockscout fork too. Blockscout team has no control over that instance. Please ask Moonriver team directly.
