### ISSUE TITLE
Template for Exchange Rate Source 

### ISSUE THREAD

**Issue by turndealer** [blockscout/blockscout#5006]
I currently see dependence on CoinGecko for exchange rate.

Could you guys provide a documentation so we can exchange_rate source, ie a template with URL option in it ..
and Default JSON format that can be read by blockscout 

Example

`{"total_supply":"2235100120.0756955","price_usd":"0.317484","volume":"5590614","price_btc":"0.00000650","volume_btc":"114.38037583","available_supply":"2235100120.0756955","btc_price":"48877.39061111","ltc_price":"154.02442575","eth_price":"3993.31098893","gbx_price":"0.03029776","usdt_price":"1.00186288","busd_price":"1.00072899","usdc_price":"1.00165795","ht_price":"9.95257902","bnb_price":"557.07651665","sol_price":"168.18236783"}`

Our plan is to provide pricing ie Price , Market Cap using own API's

**Comment by turndealer** [comment]
bump!

**Comment by vbaranov** [comment]
If you want to follow Coingecko exchange rates source implementation https://github.com/blockscout/blockscout/blob/master/apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex, JSON format should strictly follow Coingecko API implementation: https://api.coingecko.com/api/v3/coins/xdai. Otherwise, you should create your own source with the JSON format preferred for you.
