### ISSUE TITLE
The DATABASE_URL connect failed

### ISSUE THREAD

**Issue by zjb0807** [blockscout/blockscout#5331]
https://github.com/blockscout/blockscout/blob/4d6552aae30facd5ebae24d3a5f3d15936ae2fd2/apps/explorer/lib/explorer/repo/config_helper.ex#L11-L17

```
DATABASE_URL=postgresql://doadmin:password@url:port/dbname?sslmode=require
```
It seems that additional parameters are not supported, such as `sslmode=require`

**Comment by vbaranov** [comment]
@zjb0807 Not really, additional parameters do supported

<img width="662" alt="Screenshot 2022-03-18 at 09 04 38" src="https://user-images.githubusercontent.com/4341812/158946581-f5afa1df-df10-492f-9b04-d69d89d7e132.png">

**Comment by zjb0807** [comment]
@vbaranov 
I mean, the settings for SSL should be passed to the database

https://hexdocs.pm/postgrex/Postgrex.html#start_link/1-options
```
:ssl - Set to true if ssl should be used (default: false);
```

**Comment by zjb0807** [comment]
https://github.com/elixir-ecto/postgrex/issues/463

**Comment by vbaranov** [comment]
> I mean, the settings for SSL should be passed to the database

@zjb0807  ssl is true by default in prod environment (`MIX_ENV=prod`)
https://github.com/blockscout/blockscout/blob/266f503ee43436562f91b707803817f1c8243e8d/config/runtime/prod.exs#L50

until `ECTO_USE_SSL=false` is not set.

For dev and test environments, you can set `ECTO_USE_SSL=true` in order to enable SSL at DB connection.

@kj-crypto special symbols are now allowed in master branch since https://github.com/blockscout/blockscout/pull/5690

I am closing this issue for now. Please let me know if still have concerns.
