### ISSUE TITLE
Balance and transaction not shown in recipient address

### ISSUE THREAD

**Issue by mofhusseini** [blockscout/blockscout#5412]
Balance of recipient of a defi swap function (such as uniswap) `swapExactTokensForETH`, when the recipient (`to`) is different from the signer, is not updated. Also, the TX is not shown in the recipient page. 

Signature of method:
`function swapExactTokensForETH(uint amountIn, uint amountOutMin, address[] calldata path, address to, uint deadline)`

The bug happens when the `to` is different from the signer's address. 

### Environment

Docker: blockscout/blockscout:latest

### Steps to reproduce

To reproduce the issue, I created a repo with `docker-compose` and a script to make the swap at https://github.com/mofhusseini/blockscout-eth-dev. 

### Expected behaviour

The balance of the recipient should be updated.
The transaction should be shown in the recipient address page. 

### Actual behaviour

The balance is not updated and the tx does not show.

**Comment by nikitosing** [comment]
@mofhusseini I checked your example. The problem is the following: using your env BlockScout cannot fetch internal transactions. If you will use another client instead of ganache BlockScout will be able to fetch internal transactions and show correct balance. 
Also, you need to add `ETHEREUM_JSONRPC_TRACE_URL` variable, and you should change ETHEREUM_JSONRPC_VARIANT variable from `ganache` to another client or leave empty.

---------
We disabled some functions for ganache client as it does not supports correctly. Even after a long time period it still does not work, for example node crashed when I changed `ETHEREUM_JSONRPC_VARIANT` in order to fetch internal txs, BUT I tested it on your docker setup, and maybe problem in ur dockerfile or somewhere inside
