### ISSUE TITLE
CORE: <Can't download CSV file>

### ISSUE THREAD

**Issue by jellyyyyyyyyy** [blockscout/blockscout#6182]
*Describe your issue here.*

Can't download CSV file of following address's token transfers
: 0x8E71373cA1d7c3d55b511CE91a6Cf71D4cAdc60c

https://explorer.mobile-wallet.co.kr/address/0x8E71373cA1d7c3d55b511CE91a6Cf71D4cAdc60c/token-transfers?block_number=3253201&index=0&items_count=950

**Comment by vbaranov** [comment]
@jellyyyyyyyyy in order to enable CSV export page functionality, RECAPTCHA should be configured. It is managed by these ENV variables https://docs.blockscout.com/for-developers/information-and-settings/env-variables#csv-export. Please advice instance maintainers. Blockscout team doesn't manage mentioned instance.
