### ISSUE TITLE
Update Error pages

### ISSUE THREAD

**Issue by ulyanas** [blockscout/blockscout#6350]
Error to update: 
- 404
- 503 
- 422 Example: https://blockscout.com/eth/mainnet/address/0x6d2e03b7EfFEae98BD302A9F836D0d6Ab000276

**Comment by ulyanas** [comment]
@tgladilina  Please add mockups

**Comment by tgladilina** [comment]
**Errors mockup** 
https://www.figma.com/file/4In0X8UADoZaTfZ34HaZ3K/Blockscout_v1_Chakra?node-id=2673%3A91482

**404** 
Page not found
The requested page doesn’t exist or was removed! 
Back to home

![404](https://user-images.githubusercontent.com/103045386/199469211-7695a967-9bc1-42c7-954f-42b54a251cc5.png)

**500** 
Internal server error
Hang on till we get the error fixed. You may refresh the page or also try again later 
Back to home
![500](https://user-images.githubusercontent.com/103045386/199469543-e413ac6b-1dc8-4bda-a42d-7e91fbb615ac.png)

**503** 
Please try later :)
Hang on till we get the error fixed. You may refresh the page or also try again later 
Back to home
![503](https://user-images.githubusercontent.com/103045386/199469761-a22cb097-9d35-4c06-9aa7-1433ad060906.png)


**422** 
Wrong request
The request was well-formed but was unable to be followed due to semantic errors. Maybe, you mistype a hash of tx/block/address? 
Back to home
v1
![422_v2](https://user-images.githubusercontent.com/103045386/199469919-33546325-7ed9-465a-98f0-960a05de988e.png)
v2
![422](https://user-images.githubusercontent.com/103045386/199469901-5bdadb9b-bbce-478a-a76b-fe7f563495f4.png)

@ulyanas Who could check the copies? Do we need to make error's copies more friendly?

**Comment by tgladilina** [comment]
@andogro  please help us with errors texts

**Comment by andogro** [comment]
A few text suggestions:

**404 Page not found**
This page is no longer explorable! If you are lost, use the search bar to find what you are looking for.
<Return Home>

**500 Internal server error**
An unexpected error has occurred. Try reloading the page, or come back soon and try again.

**503 Service unavailable**
Hang on… we’re working on a fix! Please come back soon to try again.

**422 Request cannot be processed**
Your request contained an error, perhaps a mistyped tx/block/address hash. Try again, and check the developer tools console for more info.

**Comment by tgladilina** [comment]
@andogro  "Back to home" button without changes. Right?

**Comment by vbaranov** [comment]
@tgladilina we also have this page when requesting, for instance, inexistent tx. An example https://blockscout.com/eth/mainnet/tx/0xf2d240e5399050130ac38911b35e6d46a828b80f29b35056ef9d7c70f453ea03:

<img width="1164" alt="Screenshot 2022-11-23 at 23 45 36" src="https://user-images.githubusercontent.com/4341812/203643135-4cf30e3f-e7ec-43b7-8063-a1b6f29b39fc.png">

With the new styles, implemented by @sl1depengwyn, it looks like this:

<img width="1153" alt="Screenshot 2022-11-23 at 23 45 06" src="https://user-images.githubusercontent.com/4341812/203643238-0a9485de-6c52-460f-8ed6-b24d5ce40ecc.png">

Is this ok from your perspective? What do you mind?
a) We should keep this page in its initial state.
b) We should apply new styles to it.
c) We should modify it somehow. Please suggest an edit.

**Comment by vbaranov** [comment]
@tgladilina ping

**Comment by tgladilina** [comment]
Thank you

**Comment by tgladilina** [comment]
Mockup 
https://www.figma.com/file/WUS81pZguYJ8MMSC901n28/BS_old_layout_errors?node-id=53%3A42&t=ndquwjpx0DZrM9G2-1

<img width="750" alt="Screenshot 2022-12-03 at 17 13 35" src="https://user-images.githubusercontent.com/103045386/205445225-db151e03-3717-4642-acda-5e0897f53a1b.png">

@andogro please review the copy

**Sorry, we are unable to locate this transaction hash**

1. If you have just submitted this transaction please wait for at least 30 seconds before refreshing this page.
2. It could still be in the TX Pool of a different node, waiting to be broadcasted.
3. During times when the network is busy (i.e during ICOs) it can take a while for your transaction to propagate through the network and for us to index it.
4. If it still does not show up after 1 hour, please check with your sender/exchange/wallet/transaction provider for additional information.

Back to home
