### ISSUE TITLE
debug_traceTransaction failing when javascript tracer is not supported

### ISSUE THREAD

**Issue by tzubcic-tolar** [blockscout/blockscout#6425]
We are implementing a node that would supply blockscout with data through JSON RPC required APIs. We're having issues implementing debug_traceTransaction in its "limited" form, i.e. without support for the javascript tracer. Judging from the blockscout source, it should have support for it: https://github.com/blockscout/blockscout/blob/master/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/tracer.ex

We experienced errors in blockscout's log file while implementing the API and weren't sure about the exact expected format of the API response. What we've tried to do next is changing blockscout to send debug_traceTransaction requests without the javascript code and testing it with geth, assuming that the linked code should be able to handle geth's output without the javascript tracer. We've tried to accomplish this with the following change:

Line at https://github.com/blockscout/blockscout/blob/2a2979943c910694199c3722752f3c295d8ee1bb/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex#L79

was changed to:

    params: [hash_data, %{}]

### Environment

* Deployment type: docker-compose
* Elixir & Erlang/OTP versions (`elixir -version`): Erlang/OTP 24 [erts-12.2.1] && Elixir 1.12.2
* Node JS version (`node -v`): v12.22.9
* Operating System: Ubuntu 22.04
* Blockscout Version/branch/commit: tried commits 5ef14384dd0c8b42be8f7913ecdeefd831bc43c9 and d7177a59fbfd99ab79876bf87c245f84c9e4f4c5
* Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): geth-linux-amd64-1.10.25-69568c55

### Steps to reproduce

$ ./geth --syncmode full --gcmode archive --rinkeby --http --http.vhosts "*" --http.addr localhost --http.port 8100 --http.api "personal,net,eth,debug,txpool"

Run blockscout with docker-compose with environment pointing json rpc APIs to http://host.docker.internal:8100

### Expected behaviour

We expected tracing to work as expected.

### Actual behaviour

    blockscout | 2022-11-09T13:19:17.725 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: %FunctionClauseError{args: nil, arity: 3, clauses: nil, function: :call_op, kind: nil, module: EthereumJSONRPC.Geth.Tracer}

**Comment by tzubcic-tolar** [comment]
@vbaranov could you check if my assumption was correct? Basically, we wanted to verify that blockscout's fallback code for nodes with no support for javascript tracer works as expected. Our current assumption is that there's an issue with it as it fails with geth's output.

**Comment by maslowalex** [comment]
@tzubcic-tolar looking at the [documentation](https://geth.ethereum.org/docs/evm-tracing/builtin-tracers) it seems like the following changes will do the trick:
```elixir
params: [hash_data, %{tracer: "callTracer"}]
```
So, my point is `"debug_traceTransaction"` method expects `tracer` to be provided: https://geth.ethereum.org/docs/evm-tracing/builtin-tracers

You can pick whatever tracer suits your needs.

**Comment by cognivore** [comment]
If your geth-like EVM implementation doesn't support JS tracers, it should still have an inbuilt "callTracer" tracer, which @maslowalex mentioned.

That said, if your implementation doesn't have "callTracer", it seems like you're [out of luck](https://github.com/blockscout/blockscout/issues/5729#issuecomment-1310661987), #6474.

### If you want to understand the details of the error anyway

If you want to understand what's going on in the blockscout codebase, you should insert [trace-enabled] logging all the way from the call site in `geth.ex` to [the invocation of `step` function](https://github.com/blockscout/blockscout/blob/ad730dad0d085ef82462ab848570ab182356c221/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/tracer.ex#L47) and inspect the output.

As we can tell from the error, geth interop crashed because a 3-argument function `call_op` in module `EthereumJSONRPC.Geth.Tracer` wasn't given correct arguments. Sadly, the exception was rescued and re-raised somewhere in the code, which is considered to be bad practice in Elixir, which strips away the *actual* arguments, only leaving you with "something went wrong" level of information. I would start with commenting out seemingly relevant `rescue` statements and if it makes the system unlaunchable, resort to printing `__STACKTRACE__` in every seemingly relevant `rescue` statement.

**Comment by tzubcic-tolar** [comment]
@maslowalex @cognivore Thank you for the responses. Does that mean that I misunderstood the point of the code inside apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/tracer.ex? The comment on the top says: "for variants that don't support specifying tracer in [debug_traceTransaction]". The code handles output with "structLogs".

We started with implementation of trace API that returns data when tracer is not specified, i.e. format in the basic example given here in geth documentation: https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracetransaction That is, output when no tracer is specified.

**Comment by maslowalex** [comment]
@goodsoft Hello! Could you please elaborate on this one as an author of most of the `tracer.ex` code? Maybe we are missing / misusing something?

**Comment by goodsoft** [comment]
Frankly, I have little recollection of what is happening here, and I haven't touched Elixir for 3 years.

As for general motivation for the code in `tracer.ex`, you might want to check out the original commit description: https://github.com/blockscout/blockscout/commit/1aeea2b9cad20ad0b2a79dad2c8e26c1eb1658c3

My wild guess is that the output of your node differs from what we expect. Specifically, some pattern matching around `call_op` fails.

If you could trace the Elixir code and see, which line exactly throws, and what's the input there, this would help understanding the problem.

**Comment by vbaranov** [comment]
@tzubcic-tolar we stepped away from custom js tracer. `callTracer` is the default type of tracing of internal transactions now. It is implemented in https://github.com/blockscout/blockscout/pull/6721 and available from master branch (will be released soon). If you want to try it, please pull updates from the master branch. I am closing this issue for now. Please let me know, if you still experience the issue.
