### ISSUE TITLE
Research Blockscout internal txs tracer, when js tracer or callTracer are not supported

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#6725]

**Comment by sl1depengwyn** [comment]
So, we have one more tracer option to implement. I suggest to name it `opcode_logger` (according to geth [docs](https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers)). In order to implement it we need to adjust already existing js tracer written in elixir (https://github.com/blockscout/blockscout/blob/master/apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/tracer.ex). It would be useful for corner cases when specifying tracer in rpc is not available, however there is an important drawback in terms of perfomance, responses of this tracer are huge compared to responses of `callTracer` or `js` tracer. There is branch for playground where `opcode_logger` is hardcoded https://github.com/blockscout/blockscout/tree/mf-op-code-logger-tracer
