### ISSUE TITLE
Best practice on backuping verified contracts

### ISSUE THREAD

**Issue by strukovsky** [blockscout/blockscout#6766]
We are using blockscout in a high load blockchain and we are interested in backup of verified contracts. I've tried to encounter which tables taken from database should be dumped but I've reached no success. Could you tell please any best practices on dumping verifying contracts in e.g. `json` or `sql`? And also I'd like to now how to load this dump back to blockscout instance. Thank you in advance

**Comment by vbaranov** [comment]
In order to migrate verified smart contracts you should dump/restore 3 DB tables:
- `contract_methods`
- `smart_contracts`
- `smart_contracts_additional_sources`

_Note_: Both `smart_contracts...` tables have the foreign key on `addresses` table. Thus, if your new DB doesn't have all addresses, which those table reference, you should also dump/restore `addresses` table or only given addresses.

**Comment by strukovsky** [comment]
I've tried your instructions, it works, thank you!
