### ISSUE TITLE
Indexer stuck

### ISSUE THREAD

**Issue by Toni-d-e-v** [blockscout/blockscout#6844]
![image](https://user-images.githubusercontent.com/62844491/217586080-8b7d4de5-ced0-47dd-a3e9-734f5b28a388.png)
![image](https://user-images.githubusercontent.com/62844491/217586153-d5a7b36a-95c7-4f3d-aa34-af39167d0b1f.png)

**Comment by Toni-d-e-v** [comment]
And now its crashing
![image](https://user-images.githubusercontent.com/62844491/217586809-b6c124a2-ee16-4bec-8ff0-7243f57732d6.png)
![image](https://user-images.githubusercontent.com/62844491/217586924-44da7614-0663-4b6b-a015-3db6f13f13cc.png)

**Comment by Toni-d-e-v** [comment]
I did docker-compose down and then up
ANd now postgres is fucked up 
![image](https://user-images.githubusercontent.com/62844491/217594211-f83c3e99-f034-4cde-83c2-762873a204f0.png)

**Comment by Toni-d-e-v** [comment]
Added max conections and restarted node lets see if it will be good

**Comment by vbaranov** [comment]
@Toni-d-e-v it looks like the node, which Blockscout is connected to, doesn't contain an archival state. It should be running in archive mode. Otherwise, you need to disable fetching of internal transactions and archive balances:
```
ETHEREUM_JSONRPC_DISABLE_ARCHIVE_BALANCES=true
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true
```

As for Postgres, you can manage how capable is a DB pool size via `POOL_SIZE` env variable. By default, is 50.

I am closing this. Let me know, if you have further requests.
