### ISSUE TITLE
Transactions count issue

### ISSUE THREAD

**Issue by Bharathcoorg** [blockscout/blockscout#6955]
Project team said they had 150k transactions on day 1 and Transaction count is wrong. I am observing blocks, they have at least 8 out of 10 blocks with transactions. 
My blockscout instance is fully synced and there is no internal transactions. What's wrong here?
Is there any option to check number of transactions via RPC or WSS?
![Numbers](https://user-images.githubusercontent.com/40591495/220874752-a65ac81b-9db2-4fae-a23b-fe06578a1695.PNG)

**Comment by Bharathcoorg** [comment]
Its a substrate/parity based chain, I think there is no internal transactions.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss-testnet.5ire.network#/rpc

**Comment by vbaranov** [comment]
Then you will not be able to fetch internal transactions. You need to set `INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER=true` in order to disable such fetcher in Blockscout.

Internal transactions are not accounted in mentioned counter. If you have confirmation, that some blocks do not have transactions in Blocskcout, and they exist in RPC, please, let us know.

**Comment by Bharathcoorg** [comment]
Its working perfectly project team is wrong.
