### ISSUE TITLE
Duplications in controllers and templates on pages that have tabs

### ISSUE THREAD

**Issue by feliperenan** [blockscout/blockscout#706]
Hi team :wave:,

In the last weeks, we have been working in some tabs in the Address' page and Token's page. We noticed that there are a lot of duplications on those controllers and templates because each tab is a page that share an [overview partial](https://github.com/poanetwork/blockscout/blob/master/apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex). Then, all controllers have to duplicate the data that the partial needs and the templates have to duplicate the tabs menu.

See this example on Address' page:

### Controllers
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex#L36
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex#L16
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex#L23
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex#L36

### Templates
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex#L5
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex#L6
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex#L5
https://github.com/poanetwork/blockscout/blob/d106a2c2eeb72e01ae0696189bfaa42928f213e5/apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex#L10

When we need to add a new information in the overview, we need to care about with all controllers that share this partial. Otherwise, we are going to break some page. 

It could be worse when we need to add a new tab in one of those pages. We need to add the new tab in all templates that we already have and we need to add another duplication in the new controller to satisfy the overview section. We can see this issue more clearly on these two PRs:
- [PR 668](https://github.com/poanetwork/blockscout/pull/668/files#diff-c8dee62f6d1c79b85c16a78659101744R11)
- [PR 606](https://github.com/poanetwork/blockscout/pull/606/files#diff-e91e5ad773fa7c3c7dd10db66a0a932cR4)

**Comment by amandasposito** [comment]
### Pages that need to be refactored:

#### Address
- [ ] Transaction details page;
- [ ] Internal transaction details page;
- [ ] Not verified contract page;
- [ ] Contract verification page;
- [ ] Verified contract page;
- [ ] Token details page;

#### Transaction
- [ ] Transaction list;
- [ ] Transaction details page;
- [ ] Internal transaction details page;
- [ ] Logs;
- [ ] Token transfers page;

#### Tokens
- [ ] Token list;
- [ ] Read contract;
- [ ] Token holders;

**Comment by Lucasnar** [comment]
From this issue, we will be creating other issues to update the pages incrementally. When talking about it, we decided it is worth to create issues just to update the views, in order to remove the duplication of the tabs definition, and other issues to update the controllers. We don't have to wait for the controllers update to work on and finish the update on the views; they're fairly straightforward updates. So here is the first task:

#### First task

Refactor the templates of the pages that contain tabs in order to avoid the repetition of the code that defines the tabs. That is, move the code of the tabs definition to a partial that is loaded by the other templates, instead of duplicating the code in every template. 

Issues created to achieve that: https://github.com/poanetwork/blockscout/issues/777, https://github.com/poanetwork/blockscout/issues/778 and https://github.com/poanetwork/blockscout/issues/779.

---

After finishing this first task, we will pretty much just have to work on the controllers duplication, not having to worry about the `templates` part of this issue anymore.

**Comment by vbaranov** [comment]
Not relevant for now due to migration to the new UI.
