### ISSUE TITLE
Tokens are not being indexed properly

### ISSUE THREAD

**Issue by bretep** [blockscout/blockscout#7318]
You can see here that tokens are not being indexed properly. This began with 5.1.3. 

Both of these explorers are using the same version of blockscout, however, the v4 one began on v5.1.3 and the v3 began on v5.1.2.

Began indexing Blockscout v5.1.3: https://scan.v4.testnet.pulsechain.com/tokens

Began indexing with Blockscout v5.1.2: https://scan.v3.testnet.pulsechain.com/tokens

### Environment

Deployment type (Manual/Docker/Docker-compose): Docker
Elixir & Erlang/OTP versions (elixir -version):
Node JS version (node -v):
Operating System: Linux (Ubuntu 20.04.5 LTS (Focal Fossa))
Blockscout Version/branch/commit: v5.1.3-beta 5c9abcba8889294139743dfb2c91131f8b5b76a7
Archive node type && version (Erigon/Geth/Nethermind/Ganache/?): erigon

### Steps to reproduce

Deploy blockscout indexing mainnet with an empty Postgres database.

### Expected behaviour

Tokens are indexed properly

### Actual behaviour

Tokens are not indexed properly

**Comment by bretep** [comment]
Is there a way to force reindexing of tokens?

**Comment by vbaranov** [comment]
@bretep I initially thought, that the same chain is indexing on both explorers, but it doesn't. Not sure if it is correct to compare them since they have different transactions. I got several tokens from the top from https://scan.v4.testnet.pulsechain.com/tokens, which have no metadata, and they doesn't have new token transfers. For instance,
https://scan.v4.testnet.pulsechain.com/address/0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE/token-transfers#address-tabs
https://scan.v4.testnet.pulsechain.com/address/0xdAC17F958D2ee523a2206206994597C13D831ec7/token-transfers#address-tabs
Last token transfer is 3 months ago for both.

Once new token transfer will happen, metadata should be processed.
So, it seems no issue introduced between 5.1.2 - 5.1.3 in terms of token metadata collecting.

**Comment by vbaranov** [comment]
I see the token's metadata appeared after updating to 5.1.5. I am closing this.
