### ISSUE TITLE
cache for block count is not work proper

### ISSUE THREAD

**Issue by webdeveloper20213** [blockscout/blockscout#7499]
*The block count cache does not function properly.I tried setting it to 60 seconds as well as 1 second, but it didn't work. when new blocks are added but the count is incorrect*

### Environment

* CACHE_BLOCK_COUNT_PERIOD=60 or CACHE_BLOCK_COUNT_PERIOD=1

So, could you please help me?

**Comment by vbaranov** [comment]
@webdeveloper20213 blocks counter cannot increase immediately since it requires to calculate the count of rows in blocks table. With more rows in the table, more time it will take to calculate. Query execution can take minutes. You can calculate how long execution of `count(*) from blocks;` query takes on your DB and set appropriate value for CACHE_BLOCK_COUNT_PERIOD by following the time format https://docs.blockscout.com/for-developers/information-and-settings/env-variables#time-format.

**Comment by webdeveloper20213** [comment]
@vbaranov Thank you for your response, but my total blocks is less then 5000

**Comment by vbaranov** [comment]
How did you launch Blockscout and which version do you use?

**Comment by webdeveloper20213** [comment]
download a zip form https://github.com/blockscout/blockscout/releases/tag/v5.1.0-beta
& blockscout version id v5.1.0-beta

**Comment by vbaranov** [comment]
Would you try 5.1.4, which currently is the latest one?

**Comment by webdeveloper20213** [comment]
Is there a specific update for the count cache in this version? 
OR
In the random check at https://explorer.public.zkevm-test.net, I notice one count issue in below link 

https://explorer.public.zkevm-test.net/address/0x5f83c203bc7C6AA659F33936d8ef7386471127eE/transactions#address-tabs

in above link transactions count is 11 but the actual transaction is 22 & more then 3 day ago transaction is 14 so what is exact issue?

**Comment by vbaranov** [comment]
> Is there a specific update for the count cache in this version?

At least, it is changed how time type variables are parsed in order to support the time format, which I mentioned.

> in above link transactions count is 11 but the actual transaction is 22 & more then 3 day ago transaction is 14 so what is exact issue?

I guess, the maintainers of the instance should update the Blockscout version as well - it is a pretty old one (v4 or v3). In the previous versions that counter accounted only outgoing transactions.

**Comment by webdeveloper20213** [comment]
Okay thanks,I will try with v5.1.4 this version

**Comment by vbaranov** [comment]
I am closing this issue. Please let me know, if you still experience the issue with the latest release.
