### ISSUE TITLE
Anyway to rebuild the index while keeping user data (such as tags/contract verification results)

### ISSUE THREAD

**Issue by yarkinwho** [blockscout/blockscout#7508]
Some data in the index seems got polluted when some bug caused wrong data being returned from the chain client.

I wonder what's the proper approach to rebuild the index while keep contract verification results intact.

Thanks

**Comment by yarkinwho** [comment]
I will try, thanks, will reopen the issue if it's not working.

**Comment by yarkinwho** [comment]
Seems reindex will not fix the cached (wrong) raw_trace and the relation setup by it. e.g. a wrong address in raw trace can cause the system cannot locate creator of a contract. And this is not fixable by this approach.

So I guess I have to change my question, if I want to copy user generated data to a regenerated database, what tables should I copy?

Currently I didn't have tag enabled so I guess the "smart_contracts" table is enough?

It would be helpful to have a list of tables that I should copy if I enabled all the features. 

Thanks.

**Comment by vbaranov** [comment]
sorry for the delay in response here. There are 2 features with user data: Account functionality and smart-contract verification metadata. Tags are actually parsed from env variables or from Account functionality. Hence, if Account functionality is not enabled, in order to migrate sc verification metadata you need to migrate these tables:
- smart_contracts
- smart_contracts_additional_sources
- contract_methods
