### ISSUE TITLE
Ethereum Classic: withdrawal

### ISSUE THREAD

**Issue by jslaguartilla** [blockscout/blockscout#8008]
my first withdrawal was sucess but it didnt apper on my metamask wallet here is my wallet address 
0x468647959B0ac22D8F9a6F7FF8Af948ACd445CDC
![Screenshot_2023-07-23-07-39-13-72_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/blockscout/blockscout/assets/64562414/30b8a2c7-6b3e-4c00-b0d4-a9bfd25bc90b)
![Screenshot_2023-07-23-07-40-52-87_3ce871bb60cb313382b75690e63e41d0](https://github.com/blockscout/blockscout/assets/64562414/0ed2528b-a1f8-4afc-948c-ba987250b599)

**Comment by atapin** [comment]
@jslaguartilla here's your address on Blockscout: https://blockscout.com/etc/mainnet/address/0x468647959B0ac22D8F9a6F7FF8Af948ACd445CDC/transactions#address-tabs

Looks correct to me.
As for the Metamask – it is not the subject of this code repository. But what I see on the screenshot, is that you're looking at Ethereum Mainnet instead of Ethereum Classic. Here's the instruction on how to make Metamask work with ETC: https://ethereumclassic.org/knowledge/metamask

**Comment by vbaranov** [comment]
Please ask your question in Ethereum Classic Discord https://discord.com/invite/dwxb6nf
