### ISSUE TITLE
Email verification issue ?

### ISSUE THREAD

**Issue by Gopal-Gurram** [blockscout/blockscout#8433]
After a 5m interval I click the resent email link but get the below error. 👇

![image](https://github.com/blockscout/blockscout/assets/59303056/daf8a1f0-e204-4106-b8a0-425c7f262bdb)

**Comment by Gopal-Gurram** [comment]
@vbaranov Do we need SendGrid env variables to send a verification email?

**Comment by sl1depengwyn** [comment]
> @vbaranov Do we need SendGrid env variables to send a verification email?

Yes

**Comment by vbaranov** [comment]
> @vbaranov Do we need SendGrid env variables to send a verification email?

No, SendGrid is not required for verification email - it is sent by Auth0. Make sure Redis is working and Blockscout connected to it and you configured [account-related env vars](https://docs.blockscout.com/for-developers/configuration-options/my-account-settings) properly. I am closing this ticket. Please let us know, if the issue is still present and provide more details on your account setup, if so.
