### ISSUE TITLE
I have a problem with <docker-compose up>

### ISSUE THREAD

**Issue by cortex-zzl** [blockscout/blockscout#8779]
### Description

I am a newbie, Trying to run project
When my operating environment is ready， try docker-compose up
This error occurred
![image](https://github.com/blockscout/blockscout/assets/72853190/42daeaca-abd5-4878-9515-9ac4ee5665ab)
My running environment is linux, in a virtual machine
![image](https://github.com/blockscout/blockscout/assets/72853190/647c3eed-1ed9-4843-87a9-0a75f08428e3)

thanks

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

GETH

### Backend version

v5.3.1

### Elixir & Erlang/OTP versions

1.14.5

### Operating system

linux

**Comment by cortex-zzl** [comment]
I looked at the containers that docker is running
Is there something wrong with smart-contract-verifier?
Looks like it keeps trying to reboot
![image](https://github.com/blockscout/blockscout/assets/72853190/e5912cd5-da6e-4b5f-8a9f-1948c7b6d3a9)

**Comment by cortex-zzl** [comment]
It seems that there is a problem with the http-related configuration of smart-contract-verifier, but I don’t understand this project........

**Comment by sevenzing** [comment]
Seems like you are trying to start `smart-contract-verifier` with old ENV variables. 
I think you are using env varialbe `SMART_CONTRACT_VERIFIER__SERVER__ADDR` which is depricated (instead of `SMART_CONTRACT_VERIFIER__SERVER__HTTP__ADDR`). 

If you didn't provide this variable to service, you probably use some old version of docker-compose file of .env file. If you still cannot handle this error, please tell me how you start `smart-contract-verifier`

**Comment by cortex-zzl** [comment]
> 似乎您正在尝试`smart-contract-verifier`从旧的 ENV 变量开始。 我认为您正在使用 env varialbe `SMART_CONTRACT_VERIFIER__SERVER__ADDR`，它已被贬低（而不是`SMART_CONTRACT_VERIFIER__SERVER__HTTP__ADDR`）。
> 
> 如果您没有向服务提供此变量，您可能使用 .env 文件的某些旧版本的 docker-compose 文件。如果您仍然无法处理此错误，请告诉我您如何开始`smart-contract-verifier`

year，I updated the repository and the issue has been resolved, thank you very much.

**Comment by ekawibisono** [comment]
When finished, please close the issue
