### ISSUE TITLE
Zksync: Indexer.Block.Realtime.Fetcher terminating

### ISSUE THREAD

**Issue by vbaranov** [blockscout/blockscout#8949]
```
{"time":"2023-12-05T21:12:47.767Z","severity":"error","message":"Task #PID<0.1817.1162> started from Indexer.Block.Realtime.Fetcher terminating\n** (FunctionClauseError) no function clause matching in anonymous fn/1 in Ecto.Repo.Preloader.maybe_pmap/3\n    (elixir 1.14.5) lib/enum.ex:1662: anonymous fn/3 in Enum.map/2\n    (elixir 1.14.5) lib/enum.ex:4307: anonymous fn/3 in Enum.map/2\n    (elixir 1.14.5) lib/task/supervised.ex:370: Task.Supervised.stream_deliver/7\n    (elixir 1.14.5) lib/enum.ex:4307: Enum.map/2\nFunction: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3\n    Args: [20757212, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher
```

**Comment by devOpsTeamBM** [comment]
What with this?
I have error 
`| {"time":"2024-05-23T15:39:50.589Z","severity":"error","message":"Task #PID<0.7031.0> started from Indexer.Block.Realtime.Fetcher terminating\n** (stop) exited in: GenServer.call(Indexer.Fetcher.CoinBalance.Realtime, {:buffer, [{<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 28863553}]}, 5000)\n    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started\n    (elixir 1.14.5) lib/gen_server.ex:1027: GenServer.call/3\n    (indexer 6.6.0) lib/indexer/block/realtime/fetcher.ex:455: Indexer.Block.Realtime.Fetcher.async_import_remaining_block_data/2\n    (indexer 6.6.0) lib/indexer/block/realtime/fetcher.ex:229: Indexer.Block.Realtime.Fetcher.import/2\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 6.6.0) lib/indexer/block/fetcher.ex:342: Indexer.Block.Fetcher.import/2\n    (indexer 6.6.0) lib/indexer/block/fetcher.ex:232: Indexer.Block.Fetcher.fetch_and_import_range/3\n    (stdlib 3.17) timer.erl:166: :timer.tc/1\n    (indexer 6.6.0) lib/indexer/block/realtime/fetcher.ex:345: Indexer.Block.Realtime.Fetcher.do_fetch_and_import_block/3\nFunction: &Indexer.Block.Realtime.Fetcher.fetch_and_import_block/3\n    Args: [28863553, %Indexer.Block.Fetcher{broadcast: :realtime, callback_module: Indexer.Block.Realtime.Fetcher, json_rpc_named_arguments: [transport: EthereumJSONRPC.HTTP, transport_options: [http: EthereumJSONRPC.HTTP.HTTPoison, url: \"http://10.116.0.48:8545/\", fallback_url: nil, fallback_trace_url: nil, fallback_eth_call_url: nil, method_to_url: [eth_call: \"http://10.116.0.48:8545/\", debug_traceTransaction: \"http://10.116.0.48:8545/\", debug_traceBlockByNumber: \"http://10.116.0.48:8545/\"], http_options: [recv_timeout: 600000, timeout: 600000, hackney: [pool: :ethereum_jsonrpc]]], variant: EthereumJSONRPC.Geth], receipts_batch_size: 1, receipts_concurrency: 10}, false]","metadata":{"error":{"initial_call":null,"reason":"{{:noproc, {GenServer, :call, [Indexer.Fetcher.CoinBalance.Realtime, {:buffer, [{<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>, 28863553}]}, 5000]}}, [{GenServer, :call, 3, [file: 'lib/gen_server.ex', line: 1027]}, {Indexer.Block.Realtime.Fetcher, :async_import_remaining_block_data, 2, [file: 'lib/indexer/block/realtime/fetcher.ex', line: 455]}, {Indexer.Block.Realtime.Fetcher, :import, 2, [file: 'lib/indexer/block/realtime/fetcher.ex', line: 229]}, {:timer, :tc, 1, [file: 'timer.erl', line: 166]}, {Indexer.Block.Fetcher, :import, 2, [file: 'lib/indexer/block/fetcher.ex', line: 342]}, {Indexer.Block.Fetcher, :fetch_and_import_range, 3, [file: 'lib/indexer/block/fetcher.ex', line: 232]}, {:timer, :tc, 1, [file: 'timer.erl', line: 166]}, {Indexer.Block.Realtime.Fetcher, :do_fetch_and_import_block, 3, [file: 'lib/indexer/block/realtime/fetcher.ex', line: 345]}]}"}}}
`

**Comment by vbaranov** [comment]
The issue doesn't happen anymore. @devOpsTeamBM if the error is still present in your setup with the latest build, please open a new issue.
