### ISSUE TITLE
Metadata requires '/' to end of Base URI

### ISSUE THREAD

**Issue by sbloom-immu** [blockscout/blockscout#9204]
### Description

When setting a collections base URI for metadata - Blockscout requires a '/' at the end otherwise metadata is not indexed.
This should not be a requirement, both the below Base URIs should work:

Example 1: https://mt-test-2.s3.ap-southeast-2.amazonaws.com/metadata/nft-metadata
Example 2: https://mt-test-2.s3.ap-southeast-2.amazonaws.com/metadata/nft-metadata/

Currently only Example 2 works

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

?

### Type of the chain

L2

### Link to the page

https://explorer.testnet.immutable.com/

### Steps to reproduce

Deploy a collection on Immutable zkEVM testnet with Base URI as:https://mt-test-2.s3.ap-southeast-2.amazonaws.com/metadata/nft-metadata

Mint token ID 1.
No metadata will be indexed

### Backend version

v6.0.0-beta

### Frontend version

v1.21.2+bdd0a9f4

### Elixir & Erlang/OTP versions

Elixir

### Additional information

**User Agent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

**Comment by yvaskov** [comment]
Blockscout refers to `tokenURI` read method for metadata collection, which consists of `baseURI+tokenId`. Deploying a collection without `/` in `baseURI` results in a broken `tokenURI` link:
`https://mt-test-2.s3.ap-southeast-2.amazonaws.com/metadata/nft-metadata1` instead of `https://mt-test-2.s3.ap-southeast-2.amazonaws.com/metadata/nft-metadata/1`
