### ISSUE TITLE
Polygon zkEVM - Block removed due to chain reorganization

### ISSUE THREAD

**Issue by bap2pecs** [blockscout/blockscout#9237]
### Description

we integrated the new Blockscout UI into https://github.com/Snapchain/zkValidium-quickstart/

the transactions were showing up correctly

however, I see 404 error with message "Block removed due to chain reorganization" at `http://<REDACTED>/block/1`

<img width="1337" alt="image" src="https://github.com/blockscout/blockscout/assets/111917526/1f07ea08-a10e-44e0-8342-7201b31eb3e4">

how can we fix this?

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Polygon CDK

### Type of the chain

L2

### Link to the page

`http://<My Devserver>/block/1`

### Backend version

v6.0.0

### Frontend version

v1.22.0

### Elixir & Erlang/OTP versions

n/a

### Operating system

Ubuntu Server 22.04 LTS

**Comment by vbaranov** [comment]
This issue is related to https://github.com/blockscout/blockscout/issues/8815. I guess this is not a reorg at all. This looks like some internal indexing process dropped consensus for this block. @bap2pecs is this simply reproducible by running the latest version of the setup and sending any transaction?

**Comment by vbaranov** [comment]
Resolved by https://github.com/Snapchain/zkValidium-quickstart/pull/38

**Comment by bap2pecs** [comment]
thanks Victor!
