### ISSUE TITLE
How setup block reward

### ISSUE THREAD

**Issue by ohari5336** [blockscout/blockscout#9568]
### Description

My Blockchain based on Ethereum and in block reward based on heaving, which is described below link

https://github.com/LarissaBlockchain/Core/blob/488adb424a0a19f6bb74689d40c3cd64f6e31e85/consensus/ethash/consensus.go#L669

Also Blockchain uncle is the same as Ethereum so how do I show the block reward in the blockscout scan. It always shows zero.

### Type of the installation

Docker-compose

### Type of the JSON RPC archive node

Geth

### Backend version

Latest

### Elixir & Erlang/OTP versions

Na

**Comment by GimluCom** [comment]
You may use [`CHAIN_SPEC_PATH`](https://docs.blockscout.com/for-developers/information-and-settings/env-variables)

example json file:
```json
"engine": {
  "ethash": {
    "params": {
      "blockReward": {
        "0": "0x8AC7230489E80000",
        "2425846": "0x4563918244F40000",
        "4851692": "0x22B1C8C1227A0000",
        "7277538": "0x1158E460913D0000",
        "9703385": "0xDE0B6B3A7640000"
      }
    }
  }
}
```

**Comment by Mamu364014** [comment]
I have been dealing with kinda the same things. I'm very new to crypto and
made to many wallets and also paid the fees for crypto air drops as well as
3 nfts. I have the receipts for them I took a screenshot of. I have yet to
see any of them in any one of my wallets or anywhere. I woke up today and
looked at them and now it looks as tho they are burned. I'm so new and so
lost at this I've been so frustrated can't sleep. Lol. I was told to use my
wallet connect to link my wallet then connect then my dapp and I'd be able
to see all of my assets. Nothing has changed besides now I don't even see
them in the bkockchain no longer either. Could or does someone have the
time and knowledge to help me fix all my mess ups without losing my money.
I'm a disabled combat veteran on a very tight budget and this I started
with the very little extra funds I had to start and make my money work for
me then I f up. Sorry I am writing on your post this is way more
complicated then some make it seem and I'm way over my head.  Thank you so
much again and hope whoever can help me if anyone can doesn't get
frustrated easily because I do and I'm that lost.  Ty again.

**Comment by GimluCom** [comment]
@Mamu364014 This Github is for issues related to Blockscout. If you go to https://discord.gg/blockscout we can take a look at your issue, but there is likely nothing we can do.

**Comment by ohari5336** [comment]
> You may use [`CHAIN_SPEC_PATH`](https://docs.blockscout.com/for-developers/information-and-settings/env-variables)
> 
> example json file:
> 
> ```json
> "engine": {
>   "ethash": {
>     "params": {
>       "blockReward": {
>         "0": "0x8AC7230489E80000",
>         "2425846": "0x4563918244F40000",
>         "4851692": "0x22B1C8C1227A0000",
>         "7277538": "0x1158E460913D0000",
>         "9703385": "0xDE0B6B3A7640000"
>       }
>     }
>   }
> }
> ```

I created json file and added your content, then after setup in env and restart blockscout it's not showing block reward

**Comment by ohari5336** [comment]
Can you share sample env file, which is working

**Comment by Mamu364014** [comment]
I have nothing working. I'm not sure what I'm doing wrong but not receiving any of my crypto at all.

**Comment by Mamu364014** [comment]
I am completely knew at this and jumped in to it. Have over 2000 in crypto completely lost and not finding out anyway could be.

**Comment by vbaranov** [comment]
> Can you share sample env file, which is working

Here is the example https://github.com/blockscout/blockscout/blob/379e81afc223c8f1da3d3b7ca49b31b384f13f3b/apps/explorer/test/support/fixture/chain_spec/classic.json#L10

I am closing the issue for now. Please let us know, if the issue still presents.

**Comment by ohari5336** [comment]
I am working on the Larissa chain and our block reward change approx every week so any way to make rewards system inbuilt in blockscout so it's calculated automatically.

https://larissa.network/emission
